"""Add phase 12 models

Revision ID: 1186d44d4283
Revises: dba4466b1d0b
Create Date: 2026-09-13 22:46:25.857777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1186d44d4283'
down_revision: Union[str, None] = 'dba4466b1d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('state', sa.Enum('NEW', 'SEEN', 'SAVED', 'DISMISSED', 'APPLIED', 'EXPIRED', name='recommendationstate'), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('surfaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'job_id', name='uq_recommendation_profile_job')
    )
    op.create_index(op.f('ix_job_recommendations_job_id'), 'job_recommendations', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_recommendations_profile_id'), 'job_recommendations', ['profile_id'], unique=False)
    op.create_index(op.f('ix_job_recommendations_state'), 'job_recommendations', ['state'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_profile_id'), 'saved_searches', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_searches_profile_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_job_recommendations_state'), table_name='job_recommendations')
    op.drop_index(op.f('ix_job_recommendations_profile_id'), table_name='job_recommendations')
    op.drop_index(op.f('ix_job_recommendations_job_id'), table_name='job_recommendations')
    op.drop_table('job_recommendations')
    # ### end Alembic commands ###
