"""Add keywords and locations

Revision ID: 6483f9eab1a3
Revises: 9ec0e13a34a9
Create Date: 2026-09-12 12:35:05.814207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6483f9eab1a3'
down_revision: Union[str, None] = '9ec0e13a34a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('keywords', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('locations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'locations')
    op.drop_column('user_profiles', 'keywords')
    # ### end Alembic commands ###
