"""Add circuit breaker fields

Revision ID: 7ea3d7713917
Revises: 1186d44d4283
Create Date: 2026-09-19 19:38:58.001874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ea3d7713917'
down_revision: Union[str, None] = '1186d44d4283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    circuit_status_enum = postgresql.ENUM('CLOSED', 'OPEN', 'HALF_OPEN', name='circuitstatus', create_type=False)
    circuit_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('sources', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('consecutive_failures', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('last_status_code', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('sources', sa.Column('circuit_status', circuit_status_enum, nullable=True))
    op.add_column('sources', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_sources_circuit_status'), 'sources', ['circuit_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_circuit_status'), table_name='sources')
    op.drop_column('sources', 'next_retry_at')
    op.drop_column('sources', 'circuit_status')
    op.drop_column('sources', 'last_error')
    op.drop_column('sources', 'last_status_code')
    op.drop_column('sources', 'consecutive_failures')
    op.drop_column('sources', 'last_failure_at')
    op.drop_column('sources', 'last_success_at')
    op.drop_column('sources', 'last_attempt_at')
    op.create_table('user_profiles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('locations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_profiles_pkey')
    )
    # ### end Alembic commands ###
