"""Add source_id to provenance and unique constraint

Revision ID: 9813db964e04
Revises: 7ea3d7713917
Create Date: 2026-09-19 20:01:17.765322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9813db964e04'
down_revision: Union[str, None] = '7ea3d7713917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_prov_source_job', 'job_source_provenances', ['source_id', 'source_job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prov_source_job', 'job_source_provenances', type_='unique')
    # ### end Alembic commands ###
