"""Add Application model

Revision ID: dba4466b1d0b
Revises: 6483f9eab1a3
Create Date: 2026-09-13 18:01:16.045727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba4466b1d0b'
down_revision: Union[str, None] = '6483f9eab1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PREPARING', 'READY_FOR_REVIEW', 'APPROVED', 'SUBMITTING', 'SUBMITTED', 'SUBMISSION_STATUS_UNKNOWN', 'FAILED', 'CANCELLED', 'UNSUPPORTED', name='applicationstatus'), nullable=True),
    sa.Column('application_url', sa.String(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('unanswered_required_fields', sa.JSON(), nullable=True),
    sa.Column('submission_evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'profile_id', name='uq_application_job_profile')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_profile_id'), 'applications', ['profile_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_profile_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
