"""Add DiscoveryMethodPerformance and discovery_method to JobSourceProvenance

Revision ID: f0d46e99ab57
Revises: 9813db964e04
Create Date: 2026-09-20 00:58:16.849784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0d46e99ab57'
down_revision: Union[str, None] = '9813db964e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_method_performances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('successful_runs', sa.Integer(), nullable=True),
    sa.Column('failed_runs', sa.Integer(), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('valid_jobs', sa.Integer(), nullable=True),
    sa.Column('unique_jobs', sa.Integer(), nullable=True),
    sa.Column('duplicate_jobs', sa.Integer(), nullable=True),
    sa.Column('invalid_jobs', sa.Integer(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('failure_rate', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'method', name='uq_source_method_perf')
    )
    op.create_index(op.f('ix_discovery_method_performances_method'), 'discovery_method_performances', ['method'], unique=False)
    op.create_index(op.f('ix_discovery_method_performances_source_id'), 'discovery_method_performances', ['source_id'], unique=False)
    op.add_column('job_source_provenances', sa.Column('discovery_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_source_provenances', 'discovery_method')
    op.drop_index(op.f('ix_discovery_method_performances_source_id'), table_name='discovery_method_performances')
    op.drop_index(op.f('ix_discovery_method_performances_method'), table_name='discovery_method_performances')
    op.drop_table('discovery_method_performances')
    # ### end Alembic commands ###
