"""Add is_active to Profile

Revision ID: f8d49a2820e9
Revises: a7349f18dd6e
Create Date: 2026-09-20 09:34:08.374918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8d49a2820e9'
down_revision: Union[str, None] = 'a7349f18dd6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely add column with a server default for existing rows
    op.add_column('profiles', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_profiles_is_active'), 'profiles', ['is_active'], unique=False)
    
    # Activate at least one profile if it exists so the app doesn't break
    op.execute(
        "UPDATE profiles SET is_active = true WHERE id = (SELECT id FROM profiles LIMIT 1)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_is_active'), table_name='profiles')
    op.drop_column('profiles', 'is_active')
    op.create_table('user_profiles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('locations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_profiles_pkey')
    )
    # ### end Alembic commands ###
