"""
Discovery schemas: bounded RawJob, StrategyCandidate, DiscoveryProvenanceDTO, and error models.

These are internal ingestion contracts — NOT persistent database models.
The database models live in app/database/models.py (Job, JobSourceProvenance, JobVersion).

RawJob → (future canonicalization) → Job + JobSourceProvenance + JobVersion
"""
from pydantic import BaseModel, Field, field_validator
from typing import Optional, Dict, Any
from datetime import datetime, timezone
from enum import Enum
import json
import uuid

# ─── Field Limits ───────────────────────────────────────────────────────────

MAX_TITLE_LEN = 512
MAX_COMPANY_LEN = 256
MAX_LOCATION_LEN = 512
MAX_DESCRIPTION_LEN = 50_000  # ~50 KB text, generous but bounded
MAX_URL_LEN = 2048
MAX_SOURCE_ID_LEN = 256
MAX_STRATEGY_ID_LEN = 128
MAX_METADATA_BYTES = 16_384  # 16 KB serialized JSON limit for provider metadata


# ─── Enums ──────────────────────────────────────────────────────────────────

class CandidateState(str, Enum):
    """Tracks the lifecycle of a StrategyCandidate through the security pipeline."""
    DISCOVERED = "DISCOVERED"    # Generated by registry/strategy, NOT validated
    VALIDATED = "VALIDATED"      # Passed UrlValidator + DomainPolicy
    REJECTED = "REJECTED"        # Failed validation


class DiscoveryErrorType(str, Enum):
    """Structured error categories for discovery failures."""
    UNSUPPORTED_SOURCE = "UNSUPPORTED_SOURCE"
    CANDIDATE_REJECTED = "CANDIDATE_REJECTED"
    STRATEGY_UNAVAILABLE = "STRATEGY_UNAVAILABLE"
    ADAPTER_MISMATCH = "ADAPTER_MISMATCH"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    PARSING_FAILURE = "PARSING_FAILURE"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    MALFORMED_SOURCE_DATA = "MALFORMED_SOURCE_DATA"
    VALIDATION_FAILURE = "VALIDATION_FAILURE"
    OVERSIZED_PAYLOAD = "OVERSIZED_PAYLOAD"
    REQUIRES_BROWSER_FALLBACK = "REQUIRES_BROWSER_FALLBACK"


# ─── Structured Error ──────────────────────────────────────────────────────

class DiscoveryError(BaseModel):
    """A structured failure produced by a strategy or the pipeline."""
    error_type: DiscoveryErrorType
    strategy_id: Optional[str] = None
    adapter_id: Optional[str] = None
    candidate_id: Optional[str] = None
    message: str
    detail: Optional[str] = None


# ─── StrategyCandidate ──────────────────────────────────────────────────────

class StrategyCandidate(BaseModel):
    """
    A candidate URL discovered by the registry/strategy that must pass through
    the CandidatePipeline before it can be executed.

    CRITICAL: `state` must NEVER be set to VALIDATED by external callers.
    Only the CandidatePipeline may transition a candidate to VALIDATED.
    """
    candidate_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    strategy_id: str = Field(max_length=MAX_STRATEGY_ID_LEN)
    adapter_id: Optional[str] = Field(default=None, max_length=MAX_STRATEGY_ID_LEN)
    target_url: str = Field(max_length=MAX_URL_LEN)
    evidence: Optional[str] = Field(default=None, max_length=512)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    source: Optional[str] = Field(default=None, max_length=256)
    priority: int = Field(default=100, ge=0, le=1000)

    # Validation state — only the pipeline may set this to VALIDATED
    state: CandidateState = Field(default=CandidateState.DISCOVERED)

    # Set by the pipeline after validation
    validated_url: Optional[str] = None
    safe_ip: Optional[str] = None


# ─── DiscoveryProvenanceDTO ─────────────────────────────────────────────────

class DiscoveryProvenanceDTO(BaseModel):
    """
    Ingestion-time provenance contract. This is NOT a database model.

    Maps to the existing database model: app.database.models.JobSourceProvenance

    The canonicalization layer (future phase) will use this DTO to populate:
      Job → JobSourceProvenance → JobVersion
    """
    strategy_id: str = Field(max_length=MAX_STRATEGY_ID_LEN)
    adapter_id: Optional[str] = Field(default=None, max_length=MAX_STRATEGY_ID_LEN)
    source_type: str = Field(max_length=128)         # e.g. 'direct_ats', 'aggregator'
    source_url: str = Field(max_length=MAX_URL_LEN)
    source_job_id: Optional[str] = Field(default=None, max_length=MAX_SOURCE_ID_LEN)
    apply_url: Optional[str] = Field(default=None, max_length=MAX_URL_LEN)
    provider_name: Optional[str] = Field(default=None, max_length=256)  # e.g. 'Greenhouse'
    discovered_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ─── Bounded RawJob ─────────────────────────────────────────────────────────

class RawJob(BaseModel):
    """
    Bounded internal ingestion contract for a discovered job.

    Every field has explicit size limits. This is NOT stored in a permanent
    database table — it flows through:

        RawJob → Validation → Canonicalization → Job (PostgreSQL)

    Every RawJob carries provenance sufficient to later create:
        Job → JobSourceProvenance → JobVersion
    """
    # Provenance (required for downstream mapping)
    provenance: DiscoveryProvenanceDTO

    # Core extraction fields (bounded)
    title: str = Field(max_length=MAX_TITLE_LEN)
    company: str = Field(max_length=MAX_COMPANY_LEN)
    location: Optional[str] = Field(default=None, max_length=MAX_LOCATION_LEN)
    description: Optional[str] = Field(default=None, max_length=MAX_DESCRIPTION_LEN)
    employment_type: Optional[str] = Field(default=None, max_length=128)
    remote_status: Optional[str] = Field(default=None, max_length=64)

    # Timestamps
    posted_at: Optional[datetime] = None
    discovered_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # Bounded provider metadata
    # This captures any additional provider-specific fields (e.g. department, requisition ID)
    # Serialized size is enforced by the validator below.
    provider_metadata: Optional[Dict[str, Any]] = None

    @field_validator("provider_metadata")
    @classmethod
    def validate_metadata_size(cls, v):
        if v is not None:
            serialized = json.dumps(v)
            if len(serialized.encode("utf-8")) > MAX_METADATA_BYTES:
                raise ValueError(
                    f"provider_metadata exceeds maximum serialized size of {MAX_METADATA_BYTES} bytes"
                )
        return v


# ─── Execution Result ───────────────────────────────────────────────────────

class StrategyExecutionResult(BaseModel):
    """Structured result returned by a strategy execution."""
    strategy_id: str
    adapter_id: Optional[str] = None
    candidate_id: str
    jobs_discovered: int = 0
    requests_attempted: int = 0
    duration_seconds: float = 0.0
    raw_jobs: list[RawJob] = Field(default_factory=list)
    errors: list[DiscoveryError] = Field(default_factory=list)
    success: bool = True
